# Generated by Django 2.0.2 on 2018-02-10 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EntityName', models.CharField(max_length=255)),
                ('WikiLink', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PageEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EntityID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PanRestAPI.Entity')),
            ],
        ),
        migrations.CreateModel(
            name='WebPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('URL', models.TextField()),
                ('Content', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='pageentity',
            name='WebPageID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PanRestAPI.WebPage'),
        ),
    ]
